[build]
    publish=""
    functions="functions"
[dev]
    publish=""
    functions="functions"

[[redirects]]
    from = "/get-newsletters"
    to = "/.netlify/functions/newsletters/getNewsletters.js"
    status = 200
[[redirects]]
    from = "/add-new-newsletter"
    to = "/.netlify/functions/newsletters/addNewNewsletter.js"
    status = 200
[[redirects]]
    from = "/edit-newsletter"
    to = "/.netlify/functions/newsletters/editNewsletter.js?id=:id"
    query = { id = ":id"}
    status = 200